version: '3.8'

services:
  openresty:
    image: openresty/openresty:alpine
    container_name: openresty_server
    ports:
      - "80:80"
    # volumes:
    #   - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    #   - ./html:/usr/local/openresty/nginx/html
    #   - ./lua:/usr/local/openresty/nginx/lua
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis_server
    # ports:
    #   - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
